[package]
name = "amiigen-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiitool-rs = { version = "0.1.0" }
clap = { version = "3.2.6", features = ["derive"] }
